### ISSUE TITLE
Device not supported with more USB slots

### ISSUE THREAD

**Issue by vasyl91** [serserm/react-native-turbo-serialport#4]
I have a head unit with more USB slots what makes app receiving the error "Device not supported". It works only when I leave just one device attached. 

I initially planned to fix the source in app code but it quickly turned out that it varies randomly (one time app shows connection with device under /dev/bus/usb/001/003 other time dev/bus/usb/001/005) even though it's attached to the same USB slot. 

Any ideas or solution? Maybe there is a function, something like "search again if 'isSupported' is false"?

**Comment by SerSerch** [comment]
@vasyl91 Hi! I haven't had time to test for multi serialport yet. But I only connected one Arduino and it worked.
I did it as it was written here [felHR85/UsbSerial](https://github.com/felHR85/UsbSerial/wiki/7.-Multiple-Serial-ports)
you can also try calling listDevices, it returns [getPossibleSerialPorts](https://github.com/serserm/react-native-turbo-serialport/blob/main/packages/react-native-turbo-serialport/android/src/main/java/com/serserm/turboserialport/SerialPortBuilder.java#L260)
```
const serialport = useSerialport({
  // events callback
  onError,
  onReadData,
  onConnected,
  onDisconnected,
  onDeviceAttached,
  onDeviceDetached,
});

const {
  listDevices,
  connect,
} = serialport;

useEffect(() => {
  listDevices().then(res => {
    res.forEach(device => {
      device.isConnected().then(status => {
        // TODO
        if (!status) {
          connect(device.deviceId);
        }
      });
    });
  });
}, []);
```

Let me know if there is anything I can do to help you.

**Comment by vasyl91** [comment]
Hi, I've noticed that I can leave `useEffect` empty and it connects anyway just with `const serialport = useSerialport`. Any clues?

**Comment by vasyl91** [comment]
Hi, ok after some futile trials I finally spotted that I was using old version of the repository and now the code seems to be working but I'd have some questions. So far I tested it on a phone with single USB port.

Leaving `useEffect` emtpy changes nothing in terms of connection. It all happens in `const serialport = useSerialport`. So my idea was to prevent autoconnect. I tried this code:

```
initSerialport(config);

const config = {
  autoConnect: false,
}
```

I'm not sure if it's correct but couldn't figure out anything better (here I would like to kindly ask you to update `installation.md` and provide more usage). With `autoConnect || false,` in `packages/react-native-turbo-serialport/src/initSerialport.ts` it prevents connection. However this:

```
useEffect(() => {
  listDevices().then(res => {
    res.forEach(device => {
      device.isConnected().then(state => {
        // TODO
        if (!state) {
          device.connect();
          // the same
          // connect(device.deviceId);
        }
      });
    });
  });
}, []);
```

doesn't work anymore (works with `autoConnect || true,` ) and device remains not connected. Any ideas?

**Comment by SerSerch** [comment]
Oh, I see the bug. I try to fix it.

**Comment by vasyl91** [comment]
Also if I use `<usb-device vendor-id="9025" />`  in usb_device_filter.xml android asks every time to allow the connection with arduino. This one:

```
   <usb-device vendor-id="6790" product-id="21795" /> <!-- 0x5523: CH341A -->
   <usb-device vendor-id="6790" product-id="29987" /> <!-- 0x7523: CH340 -->
```

displays a prompt where I can save the choice and if I do app keeps crashing every time I disconnect and try to reconnect (only reinstalling helps). 

Issue not present on 1.0.1

**Comment by SerSerch** [comment]
The first version only worked with 1 usb. I completely rewrote the second version for Multiple Serial ports.

**Comment by vasyl91** [comment]
Sure but I'm sharing my observations and so far only testing it on phone with one USB (1.0.1 and 2.1.0). Both versions work, but 2.1.0 crashes app if I let it to always use the serial USB.

**Comment by SerSerch** [comment]
I will try to solve this problem, but I am not a java expert. I rewrote this module because other modules are outdated and their authors do not want to fix anything.

**Comment by SerSerch** [comment]
Hi! Please check the version 2.2.0
auto connect fixed
but still no xml fix

**Comment by vasyl91** [comment]
Hi, I didn't have an oportunity to test it in the car so far but I have noticed that app automatically disconnects when I minimize it. Is it somehow related to autoconnect turned to false?

**Comment by SerSerch** [comment]
Hi, no. this is most likely a problem with [react-native-screens](https://github.com/software-mansion/react-native-screens)
install this module and add `super.onCreate(null);`

(kotlin and java examples)
![image](https://github.com/serserm/react-native-turbo-serialport/assets/26460350/cb80d0a9-91d6-4de4-acb1-821a499ff427)

**Comment by vasyl91** [comment]
This unfortunately hasn't solved the problem :(

**Comment by vasyl91** [comment]
I found the solution! I installed version 2.1.0 and replaced files in `node_modules\@serserm\react-native-turbo-serialport` with files from 2.2.0 repository `packages/react-native-turbo-serialport`. I'll try to check it today on radio ;) thank you very much!

**Comment by vasyl91** [comment]
Nope, it still persists. Whenever I press the back button (I use it also in app with shell) it disconnects.

**Comment by SerSerch** [comment]
Hi. Please try to do the life cycle test
```js
useEffect(() => {
  Alert.alert('test', 'mount');
  return () => {
    // unmount
  };
}, []);
```
if mount appears a second time, even without a serial port, then the problem is not in the module

**Comment by SerSerch** [comment]
Hi, is there any news with a solution to the problem?

**Comment by vasyl91** [comment]
Hi, sorry for the late reply, the module works fine and the connection is very well! The problem was in React Native itself, because it's hard to maintain background processes in this environment. I had to migrate to java.
